### ISSUE TITLE
Unneeded IDE files/dirs

### ISSUE THREAD

**Issue by etangtw** [bsandhu1920/ThoughtWorks#3]
There are files and directories such as .iml and .idea that does not need to be in the repository. The repository is for storing only what's necessary to the application. I should be able to run the Java application however I choose, without worrying about any coupling between the app and the IDE.

**Comment by bsandhu1920** [comment]
I've removed the IDE related files from the repository, but I did have some difficulties getting the project to build/run when pulling down again into a new location.

I'm not sure if it's because of my inexperience with Intellij, but it took quite some time before I could get the project to run in Intellij without the .idea folder.

If you have trouble setting anything up please let me know so I can include/exclude the relevant files.

**Comment by etangtw** [comment]
Hi, Bal. No problems with cloning and running the app on my end. Try:

1) Open up IntelliJ
2) On the popup welcome menu it gives you (if it opens to an existing project instead, do File -> Close Project, then you'll get the welcome menu back), select Import Project
3) Select project dir (in your case ThoughtWorks) as the project
4) Select Create project from existing sources
5) Mash Next a bunch of times
6) Finally select Finish

From there, there were no issues running the application. See if that works.

**Comment by bsandhu1920** [comment]
Hi Eugene, gave that a go and it worked like a charm!
