### ISSUE TITLE
Naming and coupling

### ISSUE THREAD

**Issue by etangtw** [bsandhu1920/ThoughtWorks#4]
https://github.com/bsandhu1920/ThoughtWorks/blob/5dcd7e7d9a336454864bbb5f6a0076d90cea3a51/src/com/company/Triangles.java#L24

There are a few things that can be improved with this method. 

Firstly, the naming does not give me enough information. I can see it says HorizontalLine, but what about it? When working with methods and functions (going to say method from here to mean both), a good rule of thumb is to name them in terms of verbs. Methods _do_ stuff, and what they do should be explicit. Also, there are many different conventions developers adopt, but I seldom see method names be capitalised. At a glance one might confuse the method for a constructor.

Secondly, the method does two things, can you identify what they are? How might you split them up? Why would you want to split them up?

These issues apply to multiple places in the application, can you find them all?

**Comment by bsandhu1920** [comment]
Hi Eugene I can see why that would be confusing, I think I had assumed that because you had context the naming didn't need to be specific, but that will not always be the case. I've updated the methods accordingly. In regards to the naming convention it is something my old company used to do, I'm not sure if it's a C# thing but for consistencies sake I've also amended the capitalization.

I've attached a revised version of the method which I believe speaks more clearly. From what I can see the two actions being performed are the printing of the star and the counter being incremented by the loop. The printStar() method is something that could also be used elsewhere so it may be useful in that sense. Please let me know if I'm off target with this one, happy to have another look into it. 

![image](https://user-images.githubusercontent.com/8539766/36931533-e407774c-1f0b-11e8-9a0e-57c56b2d4936.png)

**Comment by etangtw** [comment]
Thanks, Bal. You are on the right track. Please push any changes up to the remote repository.

**Comment by bsandhu1920** [comment]
Hey Eugene, I've made similar changes throughout the project. Please let me know how that goes!
